### PR TITLE
Created DepthFirstSearchTraversal.py

### PR DESCRIPTION
**Pull request by abhilashkpy**
Program to peform DFS traversal in Python

### CODE REVIEW

**Comment by abhilashkpy** [comment]
C program to find the factorial of a number in a recursive way.

**Comment by RohanDas28** [comment]
Can You put them on their respective folders?

**Comment by abhilashkpy** [comment]
Hello Sir,

May I please know in which folder it is now?
I am unable to locate it.

**Comment by abhilashkpy** [comment]
Hi Sir,

Done!

Thanks

**Comment by RohanDas28** [comment]
Merged

**Pull request merged**
